DELETE https://desolate-badlands-81227.herokuapp.com/api/persons/2

###
POST https://desolate-badlands-81227.herokuapp.com/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Banana",
    "number": "040-12346"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Aaron Thoburn",
    "number": "11111111"
}


###
GET http://localhost:3001/info HTTP/1.1

###
GET http://localhost:3001/api/persons/ HTTP/1.1

###
GET http://localhost:3001/api/persons/6090e539e2a663a4c2147777 HTTP/1.1

###
DELETE http://localhost:3001/api/persons/6090e539e2a663a4c2147777

###
PUT http://localhost:3001/api/persons/6090e636b635684a5f7de94c HTTP/1.1
content-type: application/json

{
    "name": "abc",
    "number": "12345678"
}